# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_auto_20170702_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='state_province',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
