# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-01 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_auto_20170702_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='edition',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
